const notices = [
  {
    id: 1,
    title: "8/30 토요일 학원 휴무 안내",
    date: "2024-08-30",
    category: "공지사항",
    content: "학원 전체 휴무합니다.",
    author: "윤지현 원장",
    status: "공개",
    views: 45,
    priority: "높음",
    tags: ["휴무", "토요일", "안내"],
  },
  {
    id: 2,
    title: "8/15 금요일 광복절 정상 수업",
    date: "2024-08-15",
    category: "공지사항",
    content: "광복절에 정상 수업 합니다. 학원 이용에 착오가 없으시길 바랍니다.",
    author: "윤지현 원장",
    status: "공개",
    views: 38,
    priority: "높음",
    tags: ["광복절", "정상수업", "안내"],
  },
  {
    id: 3,
    title: "6/2 전체 휴무 안내",
    date: "2024-06-02",
    category: "공지사항",
    content: "6월 2일 (월) 학원 전체 휴무를 진행합니다.",
    author: "윤지현 원장",
    status: "공개",
    views: 52,
    priority: "높음",
    tags: ["휴무", "6월", "안내"],
  },
  {
    id: 4,
    title: "선거, 현충일 정상 수업 안내",
    date: "2024-06-03",
    category: "공지사항",
    content:
      "6월 3일, 6일 (화), (금) 은 정상 수업합니다. 학원 이용에 착오 없으시길 바랍니다.",
    author: "윤지현 원장",
    status: "공개",
    views: 41,
    priority: "높음",
    tags: ["선거", "현충일", "정상수업"],
  },
  {
    id: 5,
    title: "5월 5-6일 부처님 오신날 어린이날 대체 공휴일 정상 수업",
    date: "2024-05-05",
    category: "공지사항",
    content:
      "(월-화) 5월 5-6일 (월-화)은 정상 수업 합니다. 학원이용에 착오 없으시길 바랍니다 :)",
    author: "윤지현 원장",
    status: "공개",
    views: 67,
    priority: "높음",
    tags: ["부처님오신날", "어린이날", "정상수업"],
  },
  {
    id: 6,
    title: "삼일절 정상수업",
    date: "2024-05-05",
    category: "공지사항",
    content: "삼일절에 정상 수업 합니다. 학원이용에 착오 없으시길 바랍니다 :)",
    author: "윤지현 원장",
    status: "공개",
    views: 67,
    priority: "높음",
    tags: ["삼일절"],
  },
];

export default notices;
