const teachers = [
  {
    name: "윤지현 원장",
    specialty: "발성 전문가",
    experience: "15년 경력",
    education: "Medical Voice 1기 수료",
    description:
      "유명 가수 및 뮤지컬 배우, 아이돌, 실용음악과 지망생, 발성장애 환자 등 수많은 케이스에 맞춘 다양한 레슨 경험을 토대로 개인의 발성상태에 맞춘 1:1 최적화 레슨을 진행중입니다.",
    achievements: [
      "현) 서울 메디컬보이스 이비인후과 발성센터 출강 중",
      "현) 온리보컬아카데미 원장",
      "Medical Voice 1기 수료",
      "발성 전문",
      "보컬 코치",
      "발성장애 치료",
    ],
    image: "/images/온리보컬 원장 보컬코치 윤지현.jpeg",
  },
  {
    name: "한화정 부원장 보컬코치",
    specialty: "보컬 전문",
    // experience: "12년 경력",
    // education: "보컬 테크닉 전문",
    // description: "고급 보컬 테크닉 전문, 오디션 합격 다수",
    // achievements: [
    //   "고급 보컬 테크닉",
    //   "오디션 합격 다수",
    //   "음악 치료사 자격",
    //   "발성 기법 전문",
    // ],
    image: "/images/온리보컬 보컬코치 한화정.jpeg",
  },
  {
    name: "김가희 보컬코치",
    specialty: "보컬 전문",
    // experience: "10년 경력",
    // education: "실용음악과 보컬 전공",
    // description: "실용음악과 보컬 전공, 작곡 및 편곡 전문",
    // achievements: [
    //   "보컬 반주 전문",
    //   "작곡 및 편곡 전문",
    //   "음악 이론 전문",
    //   "실용음악 입시 전문",
    // ],
    image: "/images/온리보컬 보컬코치 김가희.png",
  },
  {
    name: "이다영 보컬코치",
    specialty: "보컬 전문",
    // experience: "8년 경력",
    // education: "음악학과 보컬 전공",
    // description: "음악 이론 및 시창청음 전문, 입시 준비 전문",
    // achievements: [
    //   "음악 이론 전문",
    //   "시창청음 전문",
    //   "입시 준비 전문",
    //   "화성학 전문",
    // ],
    image: "/images/온리보컬 보컬코치 이다영.jpeg",
  },
  {
    name: "배윤서 보컬코치",
    specialty: "보컬 전문",
    // experience: "6년 경력",
    // education: "앙상블 및 합창 전문",
    // description: "앙상블 및 합창 전문, 그룹 활동 지도",
    // achievements: [
    //   "앙상블 전문",
    //   "합창 지도 전문",
    //   "그룹 활동 지도",
    //   "무대 공연 전문",
    // ],
    image: "/images/온리보컬 보컬코치 배윤서.jpeg",
  },
  {
    name: "김예찬 보컬코치",
    specialty: "보컬 전문",
    // experience: "7년 경력",
    // education: "CCM 및 찬양 전문",
    // description: "CCM 및 찬양 전문, 교회 음악 전문",
    // achievements: [
    //   "CCM 전문",
    //   "찬양 지도 전문",
    //   "교회 음악 전문",
    //   "영성 음악 전문",
    // ],
    image: "/images/온리보컬 보컬코치 김예찬.jpeg",
  },
];

export default teachers;
